os: unstable

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 7

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn
  - cd app && yarn

build_script:
  - yarn package

test_script:
  - node --version
  - yarn test